# Generated by Django 6.0.4 on 2026-05-04 01:28

import account.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default_user.png', upload_to=account.models.get_upload_path)),
                ('must_change_password', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('photo', models.ImageField(blank=True, default='default_user.png', null=True, upload_to=account.models.get_upload_path)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, verbose_name='Gender')),
                ('current_academic_level', models.CharField(choices=[('G-7', 'Grade 7'), ('G-8', 'Grade 8'), ('G-9', 'Grade 9'), ('G-10', 'Grade 10'), ('G-11', 'Grade 11'), ('G-12', 'Grade 12')], max_length=10, verbose_name='Current Academic Level')),
                ('enrollment_status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], max_length=20, verbose_name='Enrollment Status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('photo', models.ImageField(blank=True, default='default_user.png', null=True, upload_to=account.models.get_upload_path)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('teacher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('JHS', 'Junior High Department'), ('SHS', 'Senior High Department')], default='JHS', max_length=50)),
                ('preferred_subject', models.CharField(choices=[('JHS-English', 'English (JHS)'), ('JHS-Math', 'Mathematics (JHS)'), ('JHS-Science', 'Science (JHS)'), ('JHS-Filipino', 'Filipino (JHS)'), ('JHS-ESP', 'Edukasyon sa Pagpapakatao'), ('JHS-MAPEH', 'Music, Art, PE, Health'), ('SHS-OralComm', 'Oral Communication'), ('SHS-GenMath', 'General Mathematics'), ('SHS-EarthLife', 'Earth & Life Science'), ('SHS-ICT', 'ICT / Empowerment Tech')], default='JHS-Math', max_length=100)),
                ('assigned_grade', models.CharField(blank=True, choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='account.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='account.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'day_of_week', 'start_time')},
            },
        ),
    ]
