"""
Django settings for my_school_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-crt*zwq76awqlf@zo_5vfl*m#)p9xdni^-*w3^7)r80+0@1gou'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'my_school_project'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_school_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'my_school_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lms_db',
        'USER': 'root',
        'PASSWORD': 'Testing123',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONNS': {
            'charset': 'ut8mb4',
            'use_unicode': True,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Burahin ang session kapag isinara ang browser tab/window
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Opsyonal: I-set kung gaano katagal bago mag-expire ang session (sa segundo)
# Halimbawa: 3600 seconds = 1 hour
SESSION_COOKIE_AGE = 3600 

# Para siguradong ma-update ang session sa bawat request
SESSION_SAVE_EVERY_REQUEST = True


LOGIN_URL = 'account:login'
LOGIN_REDIRECT_URL = 'account:student_dashboard'
LOGOUT_REDIRECT_URL = 'account:login'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py
CSRF_COOKIE_HTTPONLY = True  # 2 weeks (standard)
# This forces the browser to get a new token if the session changes
CSRF_USE_SESSIONS = True
# settings.py
SESSION_COOKIE_AGE = 600  # Session expires after 10 minutes of inactivity

# --- EMAIL CONFIGURATION (GMAIL) ---

# Use the SMTP backend to send real emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Google's SMTP server address
EMAIL_HOST = 'smtp.gmail.com'

# Port 587 is required for TLS (secure connection)
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Your Gmail address
EMAIL_HOST_USER = 'hyperzlinked@gmail.com' 

# The 16-character App Password (remove the spaces!)
EMAIL_HOST_PASSWORD = 'qyfwihkfzokjclcf' 

# The name/email that appears in the 'From' field of the user's inbox
DEFAULT_FROM_EMAIL = 'School Admin System <hyperzlinked@gmail.com>'